.dashTextToSpeech_js_metadata <- function() {
deps_metadata <- list(`dash_text_to_speech` = structure(list(name = "dash_text_to_speech",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashTextToSpeech.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTextToSpeech",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_text_to_speech` = structure(list(name = "dash_text_to_speech",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashTextToSpeech.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTextToSpeech",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_text_to_speech` = structure(list(name = "dash_text_to_speech",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_text_to_speech.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTextToSpeech",
all_files = FALSE), class = "html_dependency"),
`dash_text_to_speech` = structure(list(name = "dash_text_to_speech",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_text_to_speech.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTextToSpeech",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
